#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_graph": "00_drawgraph.ipynb",
         "quote": "00_drawgraph.ipynb",
         "Cluster": "00_drawgraph.ipynb",
         "pydot.Graph.nodes": "00_drawgraph.ipynb",
         "pydot.Graph.__getitem__": "00_drawgraph.ipynb",
         "pydot.Graph.add_item": "00_drawgraph.ipynb",
         "pydot.Graph.add_items": "00_drawgraph.ipynb",
         "pydot.Node.connect": "00_drawgraph.ipynb",
         "pydot.Graph.connect": "00_drawgraph.ipynb",
         "pydot.Graph.seq_edges": "00_drawgraph.ipynb",
         "net_colors": "00_drawgraph.ipynb",
         "show_colormap": "00_drawgraph.ipynb",
         "pydot.Graph.create_nodes": "00_drawgraph.ipynb",
         "split": "00_pagegraph.ipynb",
         "make_dot_graph": "00_pagegraph.ipynb",
         "to_dict": "00_pagegraph.ipynb",
         "DotGraph": "00_pagegraph.ipynb",
         "draw_graph": "00_pagegraph.ipynb",
         "iter_nodes": "00_pagegraph.ipynb",
         "map_": "00_pagegraph.ipynb",
         "pfx": "00_pagegraph.ipynb",
         "external_inputs": "00_pagegraph.ipynb",
         "bindings": "00_pagegraph.ipynb",
         "walk": "00_pagegraph.ipynb",
         "to_graph": "00_pagegraph.ipynb",
         "maybe_graph": "00_pagegraph.ipynb",
         "explode": "00_pagegraph.ipynb",
         "ColorMap": "00_pagegraph.ipynb",
         "Network": "00_pagegraph.ipynb",
         "to_network": "00_pagegraph.ipynb"}

modules = ["drawgraph.py",
           "pagegraph.py"]

git_url = "https://github.com/fastai/fastgraph/tree/master/"

def custom_doc_links(name): return None