#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"split": "00_core.ipynb",
         "make_dot_graph": "00_core.ipynb",
         "to_dict": "00_core.ipynb",
         "DotGraph": "00_core.ipynb",
         "draw_graph": "00_core.ipynb",
         "iter_nodes": "00_core.ipynb",
         "map_": "00_core.ipynb",
         "pfx": "00_core.ipynb",
         "external_inputs": "00_core.ipynb",
         "bindings": "00_core.ipynb",
         "walk": "00_core.ipynb",
         "to_graph": "00_core.ipynb",
         "maybe_graph": "00_core.ipynb",
         "explode": "00_core.ipynb",
         "ColorMap": "00_core.ipynb",
         "Network": "00_core.ipynb",
         "to_network": "00_core.ipynb"}

modules = ["core.py"]

git_url = "https://github.com/fastai/pagegraph/tree/master/"

def custom_doc_links(name): return None