#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Dot": "00_core.ipynb",
         "uniq_name": "00_core.ipynb",
         "quote": "00_core.ipynb",
         "graph_objects": "00_core.ipynb",
         "object_names": "00_core.ipynb",
         "add_mapping": "00_core.ipynb",
         "node_defaults": "00_core.ipynb",
         "Node": "00_core.ipynb",
         "object2graph": "00_core.ipynb",
         "obj2node_color": "00_core.ipynb",
         "graph_colors1": "00_core.ipynb",
         "graph_colors2": "00_core.ipynb",
         "cluster_defaults": "00_core.ipynb",
         "Cluster": "00_core.ipynb",
         "pydot.Graph.nodes": "00_core.ipynb",
         "pydot.Graph.__getitem__": "00_core.ipynb",
         "pydot.Graph.add_item": "00_core.ipynb",
         "pydot.Graph.add_items": "00_core.ipynb",
         "graph_items": "00_core.ipynb",
         "pydot.Graph.first": "00_core.ipynb",
         "pydot.Graph.last": "00_core.ipynb",
         "pydot.Node.with_compass": "00_core.ipynb",
         "pydot.Graph.with_compass": "00_core.ipynb",
         "pydot.Node.connect": "00_core.ipynb",
         "pydot.Graph.connect": "00_core.ipynb",
         "graph_edges_seq": "00_core.ipynb",
         "pydot.Graph.add_edges_seq": "00_core.ipynb",
         "seq_cluster": "00_core.ipynb",
         "Point": "00_core.ipynb"}

modules = ["core.py"]

git_url = "https://github.com/fastai/fastdot/tree/master/"

def custom_doc_links(name): return None